###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: filenet-fncm-operator
  labels:
    app.kubernetes.io/instance: ibm-fncm
    app.kubernetes.io/managed-by: ibm-fncm
    app.kubernetes.io/name: ibm-fncm
    release: 5.5.8
roleRef:
  name: ibm-fncm-operator
subjects:
- kind: ServiceAccount
  name: ibm-fncm-operator
  namespace: filenet