apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cp4a-shared-log-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "{{ RWX StorageClass name }}"
  resources:
    requests:
      storage: 100Gi
  volumeName: cp4a-shared-log-pv