apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 4 
mirror:
  platform:
    channels:
      - name: stable-4.10 
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10 
storageConfig: 
  registry:
    imageURL: bastion.localhost:8443/oc-mirror
    skipTLS: true
