replicaCount: 1
env:
  LDAP_ORGANISATION: "cp.local"
  LDAP_DOMAIN: "cp.local"
global:  
  adminPassword: 'Password'
  configPassword: 'Password'
customLdifFiles:
  01-sds-schema.ldif: |-
    dn: cn=sds,cn=schema,cn=config
    objectClass: olcSchemaConfig
    cn: sds
    olcAttributeTypes: {0}( 1.3.6.1.4.1.42.2.27.4.1.6 NAME 'ibm-entryUuid' DESC 
      'Uniquely identifies a directory entry throughout its life.' EQUALITY caseIgnoreMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 SINGLE-VALUE )
    olcObjectClasses: {0}( 1.3.6.1.4.1.42.2.27.4.2.1 NAME 'sds' DESC 'sds' SUP top AUXILIARY MUST ( cn $ ibm-entryuuid ) )
  02-default-users.ldif: |-
    # Units
    dn: ou=Users,dc=cp,dc=local
    objectClass: organizationalUnit
    ou: Users

    dn: ou=Groups,dc=cp,dc=local
    objectClass: organizationalUnit
    ou: Groups

    # Users
    dn: uid=cpadmin,ou=Users,dc=cp,dc=local
    objectClass: inetOrgPerson
    objectClass: sds
    cn: cpadmin
    sn: cpadmin
    uid: cpadmin
    mail: cpadmin@cp.local
    userpassword:: UGFzc3dvcmQ=
    employeeType: admin
    ibm-entryuuid: e6c41859-ced3-4772-bfa3-6ebbc58ec78a


    dn: uid=cpuser,ou=Users,dc=cp,dc=local
    objectClass: inetOrgPerson
    objectClass: sds
    cn: cpuser
    sn: cpuser
    uid: cpuser
    mail: cpuser@cp.local
    userpassword:: UGFzc3dvcmQ=
    ibm-entryuuid: 30183bb0-1012-4d23-8ae2-f94816b91a75

    # Groups
    dn: cn=cpadmins,ou=Groups,dc=cp,dc=local
    objectClass: groupOfNames
    objectClass: sds
    cn: cpadmins
    member: uid=cpadmin,ou=Users,dc=cp,dc=local
    ibm-entryuuid: 4196cb9e-1ed7-4c02-bb0d-792cb7bfa768    

    dn: cn=cpusers,ou=Groups,dc=cp,dc=local
    objectClass: groupOfNames
    objectClass: sds
    cn: cpusers
    member: uid=cpadmin,ou=Users,dc=cp,dc=local
    member: uid=cpuser,ou=Users,dc=cp,dc=local
    ibm-entryuuid: fc4ded27-8c6a-4a8c-ad9e-7be65369758c
replication:
  enabled: false
persistence:
  enabled: true
  accessModes:
    - ReadWriteMany
  size: 8Gi
  storageClass: "ocs-storagecluster-cephfs"
livenessProbe:
  initialDelaySeconds: 60
readinessProbe:
  initialDelaySeconds: 60
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
ltb-passwd:
  enabled: false
phpldapadmin:
  enabled: true
  ingress:
    enabled: false
  env:
    PHPLDAPADMIN_LDAP_HOSTS: "openldap.openldap.svc.cluster.local"
